### ISSUE TITLE
Leak in DrRacket

### ISSUE THREAD

**Issue by rfindler** [Metaxal/quickscript#70]
It looks like [this commit](https://github.com/Metaxal/quickscript/commit/d9e82814c3192b519b4ac1f550ec849c4bbeb705) causes a leak in DrRacket. Here is the [first drdr failure](http://drdr.racket-lang.org/64120/racket/share/pkgs/drracket-test/tests/drracket/no-write-and-frame-leak.rkt).

**Comment by rfindler** [comment]
I'm not seeing why this commit changed the story (although it could just be that the test isn't good enough) but [this line](https://github.com/Metaxal/quickscript/blob/master/tool.rkt#L129) is suspicious. What cleans up the variable `drr-frame` to make sure that it doesn't hold onto a frame after the frame is closed?

**Comment by rfindler** [comment]
Getting rid of a global variable that holds onto a frame sounds great to me. If you want to see if the test starts passing with that change without pushing it, you can run this:
```
% racket -l  tests/drracket/no-write-and-frame-leak
```

**Comment by Metaxal** [comment]
Isn't this a better command btw?
```shell
raco test --drdr -l  tests/drracket/no-write-and-frame-leak
```

**Comment by rfindler** [comment]
> Seems to be working now, thanks!

Great, thank you! Just to confirm: the commit that made drdr upset didn't get into the release branch for quickscript, did it? (If it did, we should think about putting the fix on the release branch too, I'd say.)

> Isn't this a better command btw?
> 
> ```shell
> raco test --drdr -l  tests/drracket/no-write-and-frame-leak
> ```

I think that works too.

**Comment by Metaxal** [comment]
I just pushed to master, I'm not sure what commit is used for the next release. 
IIUC, hooks are not yet part of the release:
http://pre-release.racket-lang.org/status/?repo=Metaxal/quickscript
I think I prefer it this ways though, so that I have more time to use it and tweak it.

**Comment by rfindler** [comment]
Sounds good. Thanks!

**Comment by rfindler** [comment]
Several days later, drdr is still failing and has not picked up the change to quickscript. @Metaxal can you click on the "refresh my packages" button on the pkg server?

**Comment by Metaxal** [comment]
Done
